### ISSUE TITLE
File descriptor leaks for harness.log and task.log files.

### ISSUE THREAD

**Issue by jchecahi** [beaker-project/restraint#292] opened 2023-03-24 13:33 UTC
When scheduling and running a beaker job (from the beaker WebUI), a pair of `harness.log` and `task.log` file descriptors will be left open for each task run in a recipe.
This can be checked running a command `ls -la /proc/<restraintd-pid>/fd` after each task, or logging into the provisioned system after the recipe has run, and checking manually which descriptors has restraintd opened.

However, taking the very same job xml that triggers this behavior, and running it from a remote machine using restraint-client doesn't trigger this issue and the file descriptors are not leaked. Even when reusing the system where the leaks were reproduced.

**Comment by wackrat** [comment] 2023-03-26 14:00
A recent Beaker [log file](https://beaker.engineering.redhat.com/recipes/13605631/logs/program.log) includes the following excerpt.
```
13:14:00,137 INF program: Installing       : restraint-0.4.0-1.el9.aarch64                        61/78
```
Version [restraint-0.4.0](https://github.com/restraint-harness/restraint/tree/restraint-0.4.0/src) predates #216, which made it into [restraint-0.4.1](https://github.com/restraint-harness/restraint/tree/restraint-0.4.1/src).

Upgrading the `restraint` package in Beaker should cure this, in which case this issue is a duplicate of #215.

Perhaps the remote machine mentioned here has a newer version of the `restraint` package.

**Comment by jchecahi** [comment] 2023-03-27 14:33
@wackrat thanks for your comment. You are right, I was running restraint-client-0.4.2 on my workstation.

**Closed as not planned** 2023-03-27 14:33 UTC
