### ISSUE TITLE
restraint client received SIGPIPE

### ISSUE THREAD

**Issue by wizardofoz123** [beaker-project/restraint#173] opened 2020-10-29 20:05 UTC
Hi,

during a kernel testing on a specific hardware, restraint client receives SIGPIPE signal and is killed. 

$ restraint --conn-retries 15 --job /tmp/tmpprnoooe8/job.xml --rsh "ssh -o StrictHostKeyChecking=no" --host 8993063=root@<redacted!>
[<redacted!>] T:      14 [IOMMU boot test                            ] Running
[<redacted!>] Connection to <redacted!> closed by remote host.
Disconnected.. delaying 60 seconds. Retry 1/15.
Connecting to host: root@<redacted!>, recipe id:8993063
Thread 1 "restraint" received signal SIGPIPE, Broken pipe.
0x00007ffff6e03af7 in write () from /lib64/libpthread.so.0
(gdb)

This happens with restraint-client-0.3.1-1.fc32eng.x86_64 and restraint-client-0.3.0-1.el8bkr.x86_64, possibly others. It looks to be well-reproducible.

Is this issue on the radar? Can anyone look into this, or can I get some help debugging this?

Thanks.

**Comment by wizardofoz123** [comment] 2020-10-30 15:41
@cbouchar

**Comment by cbouchar** [comment] 2020-11-03 16:27
This doesn't sound like a restraint software issue but an environment issue where the communication path between the client and server is getting broken.

**Comment by wizardofoz123** [comment] 2020-11-05 20:05
Update: looks like this keeps happening with a specific test. Will create a reproducer, look at the code and ask the maintainer of the test itself.

**Comment by wizardofoz123** [comment] 2021-03-21 13:00
We keep hitting this in the pipeline.

The issue isn't limited to a specific test.

**Comment by wizardofoz123** [comment] 2021-03-24 11:39
@cbouchar Can you suggest some way to debug this? 

I've tried reproducing with specific tests and versions, but I haven't had luck. I'll try using specific machines as well.

**Comment by cbouchar** [comment] 2021-03-24 12:02
@wizardofoz123 I am aware of your problem but have work ahead of it.

**Comment by cbouchar** [comment] 2021-03-25 19:54
It would be interesting to add --timeout 15 to your client command line.  Currently the ssh connection between client and
server defaults to 5.  Give it more time and let's see how it behaves.

**Comment by wizardofoz123** [comment] 2021-03-26 13:28
Thanks for suggesting this!

Looks like the problem _might_ be that we're using `--rsh` option, which throws away default restraint timeout settings and all we need to do is add `-o ServerAliveInterval=60 -o ServerAliveCountMax=5`  to it to have default settings.

Waiting on pipeline results to see if this resolves the problem.

**Comment by cbouchar** [comment] 2021-03-26 13:45
Very cool!  Let's hope you didn't speak too soon.  Please let me know results.

**Comment by cbouchar** [comment] 2021-03-29 11:53
Can this issue be closed?

**Comment by wizardofoz123** [comment] 2021-03-29 13:00
@cbouchar  Unfortunately not, I see SIGPIPE with multiple systems, followed by kernel panic and EWD hit in Beaker.

**Comment by wizardofoz123** [comment] 2021-03-29 15:31
This also often happens when a test reboots the system.

**Comment by cbouchar** [comment] 2021-03-29 20:02
In your client command line, do you have --p 8081 to specify a fix port for restraintd(server) to listen on?

**Comment by wizardofoz123** [comment] 2021-03-30 10:32
@cbouchar No, I don't, all client invocations look like:
`restraint --conn-retries 15 --job /tmp/tmpl_mczffm/job.xml --rsh "ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=5 -o StrictHostKeyChecking=no" --host 1234=root@<hostname>`

**Comment by cbouchar** [comment] 2021-03-30 18:58
I'm unable to reproduce your issue.  What restraint version are you running on the server side?

**Comment by StykMartin** [comment] 2021-03-31 08:01
I'm quite Jakub is not providing FQDN(s) on purpose. We shouldn't leak it to the public.

**Comment by wizardofoz123** [comment] 2021-03-31 08:59
RPM version:
 restraint               aarch64  0.3.2-1.el8bkr        beaker-harness

Martin is right, I'm not providing FQDN(s) on purpose. Although I _think_ they may be shared publicly, I still prefer to not provide them.
Sending more info over email for purposes of reproducing the issue.

Also, specifying port by hand using `-p 8082` does not solve the problem. restraint client is still SIGPIPEd, occasionally masking issues and kernel panics.

**Comment by cbouchar** [comment] 2021-07-26 20:00
Solution merged.
https://github.com/beaker-project/restraint/pull/229

**Closed by cbouchar** 2021-07-26 20:00 UTC
