### ISSUE TITLE
 PTY needed for ausearch after 0.2.0 upgrade

### ISSUE THREAD

**Issue by The-Mule** [beaker-project/restraint#24] opened 2020-04-09 09:20 UTC
Beaker tasks for audit testing usually consist of adding some audit rule, generating audit event and then using ausearch to check that event was logged in audit log. Hence we usually follow this scheme in runtest.sh:

rlRun "auditctl -a ..." 0 "Add rule catching event X"
rlRun "..." 0 "Do some action o trigger event X"
rlRun "ausearch ..." 0 "Check that event X was logged"

Previously, with restraint 0.1.45, we were running beaker tasks for audit testing without issues.

Now with restraint-0.2.0 all tests started failing. RHEL version is the same, audit and kernel packages are the same, the only difference is the version of restraint. All ausearch commands fail, no events are found even after 30 seconds waiting.

However, when the beaker machine is reserved and test is executed manually by running 'make run' in ssh spawned shell in the machine, all tests pass correctly (without waiting). This usually seems to indicate that (pseudo)terminal is needed. Indeed, when ausearch is executed by 'unbuffer' then tests pass in beaker too:

rlRun "unbuffer ausearch ..." 0 "Check that event X was logged"

Clearly, ausearch need some kind of tty/pty or some other IO mechanism in place to work. Since it was working in 0.1.45 there must be some change related to IO between 0.1.45 and 0.2.0. I tried to bisect commits and it seems to stop working after some of the following commits:

o Remove libssh from restraint client
o Add pkg_commands.d files for debian and ubuntu
o Replace rhts-sync cmds with rstrnt-sync-... cmds
o Remove execute permission from systemd service file

I suspect that removing libssh might be the change breaking our tests.

Can you please help me understand what changed? Was the change intentional? Hundreds of tests are using ausearch command and it would be expensive and risky to change all of them. If we need to do it, we need to understand why.

**Comment by StykMartin** [comment] 2020-04-09 09:34
This definitely may be connected with a code change where we removed LIBSSH. There is a lot of changes regarding IO. @cbouchar can you look into it?

- Failing  `J:4184515`
- Passing `J:4184628`

**Comment by thrix** [comment] 2020-04-15 06:56
Oh, we migrated just to 0.2.0 and missed this issue. This is unfortunate. Can somebody please investigate this with priority? This might hit us hard in CI

**Comment by cbouchar** [comment] 2020-04-15 11:44
Investigating now.

**Comment by sopos** [comment] 2020-04-15 14:07
Why ausearch relies on PTY? Isn't it a bug of ausearch as well?

**Comment by thrix** [comment] 2020-04-15 16:27
@sopos yeah, I believe @The-Mule is reporting that internally ... but anyway, it is not feasible to fix all RHELs :)

**Comment by WOnder93** [comment] 2020-04-16 08:31
It's not a bug, it's just a really confusing "feature". Basically, ausearch checks if stdin is something other than TTY and in that case reads the records from there instead of the system audit logs. It is supposed to be for convenience so that you can do e.g. `grep something audit.log | ausearch -m AVC` to read from a pipe, but `ausearch -m AVC` to read from the system logs. (Yes, this is horrible, but unfortunately that's how it works...) There is an `--input-logs` option that forces ausearch to read from the system logs regardless of what stdin is linked to. That is more appropriate than using `unbuffer`.

IMHO the tests should not rely on what the testing system gives them for stdin and should just always use `--input-logs` whenever expecting ausearch to read the system logs. So... sorry @The-Mule, but looks like you'll have to fix the tests :)

**Comment by The-Mule** [comment] 2020-04-16 09:55
@WOnder93 Ondro, thanks for perfect explanation. Now it is starting to make sense to me. I am not hesitant to fix the test as long as there is a good rationale behind it and I consider the one you suggested to be a good one. 

I am just wondering what stdin is in restraint-0.2.0.

I did a quick check to see if tty was present in 0.1.45 and 0.2.0 and there is none (I just run 'tty' command in the test) and both old and new version outputs "not a tty". The last thing I would love to understand is difference in stdin in 0.1.45 and 0.2.0.

**Comment by thrix** [comment] 2020-04-16 10:22
Still :) this is a change of behaviour that can break a lot of tests, it is not just about @The-Mule :) I would definitely opt so we fix restraint so it behaves as before, if that is not possible, than go back to changing a lot of tests :)

**Comment by cbouchar** [comment] 2020-04-16 12:19
Hi Ondrej:

I ran into issues running the rpm you provided me yesterday.  I wrote my
own task and it performs a fetch operation and what I'm seeing is
'ausearch' also failed in 0.1.45 for me.  I'm also working from the
development beaker.  Here is my job.  Can you see the difference?

https://beaker-devel.app.eng.bos.redhat.com/jobs/18535

Carol

**Comment by cbouchar** [comment] 2020-04-16 12:32
Let me try to be clearer.  Can you see the difference between my task and
yours? Why behavior difference?

Carol

**Comment by cbouchar** [comment] 2020-04-17 10:17
I'm seeing the discrepancy appear when I remove the 'glib update'.  It
doesn't appear to be an issue with removal of sshlib.
Stay tuned as I'm doing further testing to confirm.

Carol

**Comment by cbouchar** [comment] 2020-04-17 14:08
Yes I've since confirmed issue in rm sshlib.  My previous workspace used was sick.

**Comment by danrodrig** [comment] 2020-04-17 14:34
There are some changes in IO for process in 0.2.0, and these are causing this issue, and #26 too. I made draft PR #40 for this, that reverts handling of IO. I tested it in our devel instance, and it passes. The jobs are:
- `J:18537` with current 0.2.0, it fails
- `J:18540` with #40, it passes

It is fixing also #26 

I'll finish the draft, and if nothing else appears, should be fixed next week.

**Comment by danrodrig** [comment] 2020-04-29 11:21
This issue is fixed in #50. Verified in our internal Beaker devel instance, `J:18600`.

**Comment by The-Mule** [comment] 2020-04-30 07:21
I can confirm this - https://beaker.engineering.redhat.com/jobs/4230495. Thanks a lot! Feel free to close this one as resolved once the fixed restraint is in production.

**Comment by danrodrig** [comment] 2020-04-30 10:12
> I can confirm this - https://beaker.engineering.redhat.com/jobs/4230495. Thanks a lot! Feel free to close this one as resolved once the fixed restraint is in production.

Thanks for the feedback, @The-Mule. This issue will be closed by GitHub after #50 is merged. Internal deployments are not tracked here.

**Closed** 2020-04-30 12:05 UTC
